export const biliData = {
	example: true,
	code: 0,
	msg: 'ok',
	message: 'ok',
	data: {
		uid: 473013658,
		room_id: 22590024,
		short_id: 0,
		attention: 1636,
		online: 0,
		is_portrait: false,
		description: '顺德一中晚会直播',
		live_status: 0,
		area_id: 372,
		parent_area_id: 11,
		parent_area_name: '知识',
		old_area_id: 6,
		background: '',
		title: 'bilibili主播的直播间',
		user_cover:
			'https://i0.hdslb.com/bfs/live/new_room_cover/077d3a412e50d17b06d471142f6fb2ee4ebf8664.jpg',
		keyframe: 'https://i0.hdslb.com/bfs/live-key-frame/keyframe051722000000225900247o3yeu.jpg',
		is_strict_room: false,
		live_time: '0000-00-00 00:00:00',
		tags: '校园,晚会,顺德一中,DV,DV社',
		is_anchor: 0,
		room_silent_type: '',
		room_silent_level: 0,
		room_silent_second: 0,
		area_name: '校园学习',
		pendants: '',
		area_pendants: '',
		hot_words: [
			'2333333',
			'喂，妖妖零吗',
			'红红火火恍恍惚惚',
			'FFFFFFFFFF',
			'Yooooooo',
			'啪啪啪啪啪',
			'666666666',
			'老司机带带我',
			'你为什么这么熟练啊',
			'gg',
			'prprpr',
			'向大佬低头',
			'请大家注意弹幕礼仪哦！',
			'还有这种操作！',
			'囍',
			'打call',
			'你气不气？',
			'队友呢？'
		],
		hot_words_status: 0,
		verify: '',
		new_pendants: {
			frame: {
				name: '',
				value: '',
				position: 0,
				desc: '',
				area: 0,
				area_old: 0,
				bg_color: '',
				bg_pic: '',
				use_old_area: false
			},
			badge: null,
			mobile_frame: {
				name: '',
				value: '',
				position: 0,
				desc: '',
				area: 0,
				area_old: 0,
				bg_color: '',
				bg_pic: '',
				use_old_area: false
			},
			mobile_badge: null
		},
		up_session: '',
		pk_status: 0,
		pk_id: 0,
		battle_id: 0,
		allow_change_area_time: 0,
		allow_upload_cover_time: 0,
		studio_info: {
			status: 0,
			master_list: []
		}
	}
};
